#!/bin/bash

set -e

sudo systemctl enable anydesk
sudo systemctl start anydesk
sudo systemctl enable arpwatch
sudo systemctl start arpwatch
sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon
sudo systemctl enable bacula-fd
sudo systemctl start bacula-fd
sudo systemctl enable bacula-sd
sudo systemctl start bacula-sd
sudo systemctl enable bluetooth
sudo systemctl start bluetooth
sudo systemctl enable ceph-fuse.target
sudo systemctl start ceph-fuse.target
sudo systemctl enable clamav-daemon
sudo systemctl start clamav-daemon
sudo systemctl enable clamav-freshclam
sudo systemctl start clamav-freshclam
sudo systemctl enable cups-browsed
sudo systemctl start cups-browsed
sudo systemctl enable cups
sudo systemctl start cups
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl enable etc-setserial
sudo systemctl start etc-setserial
sudo systemctl enable hostapd
sudo systemctl enable irqbalance
sudo systemctl start irqbalance
sudo systemctl enable lm-sensors
sudo systemctl start lm-sensors
sudo systemctl enable ntp
sudo systemctl start ntp
sudo systemctl enable o2cb
sudo systemctl start o2cb
sudo systemctl enable ocfs2
sudo systemctl start ocfs2
sudo systemctl enable openvpn
sudo systemctl start openvpn
sudo systemctl enable remote-fs.target
sudo systemctl start remote-fs.target
sudo systemctl enable rsync
sudo systemctl start rsync
sudo systemctl enable setserial
sudo systemctl start setserial
sudo systemctl enable ssh
sudo systemctl start ssh
sudo systemctl enable sysstat
sudo systemctl start sysstat
sudo systemctl enable smartmontools
sudo systemctl start smartmontools
sudo systemctl enable teamviewerd
sudo systemctl start teamviewerd
sudo systemctl enable zfs-fuse
