#!/bin/bash

# Wrapper script required for custom polkit pkexec policy
#
# First argument is the path to the script to be executed

SCRIPTPATH=$(readlink -e "$1")

# Change working directory to script directory
cd "$(dirname "$SCRIPTPATH")" || exit 127

exec "$SCRIPTPATH"
