#!/bin/bash

set -e

sudo systemctl disable anydesk
sudo systemctl stop anydesk
sudo systemctl disable arpwatch
sudo systemctl stop arpwatch
sudo systemctl disable avahi-daemon
sudo systemctl stop avahi-daemon
sudo systemctl disable bacula-fd
sudo systemctl stop bacula-fd
sudo systemctl disable bacula-sd
sudo systemctl stop bacula-sd
sudo systemctl disable clamav-daemon
sudo systemctl disable bluetooth
sudo systemctl stop bluetooth
sudo systemctl disable ceph-fuse.target
sudo systemctl stop ceph-fuse.target
sudo systemctl stop clamav-daemon
sudo systemctl disable clamav-freshclam
sudo systemctl stop clamav-freshclam
sudo systemctl disable cups-browsed
sudo systemctl stop cups-browsed
sudo systemctl disable cups
sudo systemctl stop cups
sudo systemctl disable docker
sudo systemctl stop docker
sudo systemctl disable etc-setserial
sudo systemctl stop etc-setserial
sudo systemctl disable hostapd
sudo systemctl stop hostapd
sudo systemctl disable irqbalance
sudo systemctl stop irqbalance
sudo systemctl disable lm-sensors
sudo systemctl stop lm-sensors
sudo systemctl disable ntp
sudo systemctl stop ntp
sudo systemctl disable o2cb
sudo systemctl stop o2cb
sudo systemctl disable ocfs2
sudo systemctl stop ocfs2
sudo systemctl disable openvpn
sudo systemctl stop openvpn
sudo systemctl disable remote-fs.target
sudo systemctl stop remote-fs.target
sudo systemctl disable rsync
sudo systemctl stop rsync
sudo systemctl disable setserial
sudo systemctl stop setserial
sudo systemctl disable ssh
sudo systemctl stop ssh
sudo systemctl disable sysstat
sudo systemctl stop sysstat
sudo systemctl disable smartmontools
sudo systemctl stop smartmontools
sudo systemctl disable teamviewerd
sudo systemctl stop teamviewerd
sudo systemctl disable zfs-fuse
sudo systemctl stop zfs-fuse
